// Mocks generated by Mockito 5.4.6 from annotations
// in send_money_app/test/mocks/mock_api_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async';

import 'package:mockito/mockito.dart';
import 'package:send_money_app/presentation/data/data_sources/api_service.dart';
import 'package:send_money_app/presentation/data/models/transaction_model.dart';

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends Mock implements ApiService {
  MockApiService() {
    throwOnMissingStub(this);
  }

  @override
  Future<bool?> postTransaction(TransactionModel? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#postTransaction, [transaction]),
            returnValue: Future<bool?>.value(),
          )
          as Future<bool?>);

  @override
  Future<List<TransactionModel>> fetchTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTransactions, []),
            returnValue: Future<List<TransactionModel>>.value(
              <TransactionModel>[],
            ),
          )
          as Future<List<TransactionModel>>);
}
